name: PR Preview Site
on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install --upgrade pip

      - name: Build Preview Site
        run: |
          python scripts/build_site.py dist

      - name: Deploy to GitHub Pages (Preview)
        uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 这里必须是 GH_PAT
          publish_dir: dist
          destination_dir: pr/${{ github.event.pull_request.number }}
          commit_message: "Deploy preview for PR #${{ github.event.pull_request.number }}"
